[package]
name = "pl-coreutils"
version = "0.1.0"
edition = "2021"
authors = ["Peter Lahanas"]

[build]
target-dir = "$HOME/pl-bin"

[workspace]

[dependencies]
assert_cmd = "2.0.16"
clap = { version = "4.5.31", features = ["derive"] }
predicates = "3.1.3"
